config/routes.rb
Rails.application.routes.draw do

  root to: 'users#homepage'

  resources :contracts
  resources :request_jobs
  resources :request_services
  resources :services
  resources :admins
  resources :clients
  resources :aides
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #HomePage 
  get '/home', to: 'users#homepage'
  # AboutPage 
  get '/about', to: "users#about"


# SERVICES 
get "/careers/:id", to: "services#career", as: 'career_path'


# GET THE AIDE THE LOGIN FORM
get "/login", to: "aides#login", as: "login"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here", to: "aides#handle_login"
delete "/logout", to: "aides#logout", as: "logout"
get "/profile", to: "aides#profile", as: "profile"


# GET THE CLIENT THE LOGIN FORM
get "/login_2", to: "clients#login", as: "login_2"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_2", to: "clients#handle_login"
delete "/logout_2", to: "clients#logout", as: "logout_2"
get "/my_profile", to: "clients#my_profile", as: "my_profile"


# GET THE ADMIN THE LOGIN FORM
get "/login_3", to: "admins#login", as: "login_3"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_3", to: "admins#handle_login"
delete "/logout_3", to: "admins#logout", as: "logout_3"
get "/admin_profile", to: "admins#profile", as: "admin_profile"

# EXTRA RENDER FOR SERVICES CONTROLLER 
get "jobs", to: 'services#job', as: 'jobs'

end

app/views/admins/admin_profile.html.erb
<div class="customized-container">
    <h2> Hello <%= @current_admin.first_name %> <br> This is your admin profile </h2>
    <br><br>
    
    <div class="container">
        <div class="row">
            <div class="col-md-6">
              <div class="card-body">
                <h4 class="card-title"><strong>All Clients</strong></h4>
                  <% @clients.map do |client| %> 
                    <p class="card-text"><%= client.first_name %> <%= client.last_name %> </p>
                  <% end %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card-body">
                <h4 class="card-title"><strong>All Aides</strong></h4>
                  <% @aides.map do |aide| %> 
                    <p class="card-text"><%= aide.first_name %> <%= aide.last_name %> </p>
                  <% end %>
              </div>
            </div>
        </div>
    </div>

  <br><br>

  <h2 class= "text-center"> All Contracts </h2>
    <% @contracts.map do |contract| %> 
      <table class="table table-info">
        <thead>
          <tr>
            <th scope="col">Service</th>
            <th scope="col">availability to start</th>
            <th scope="col">Aide</th>
            <th scope="col">Gender</th>
            <th scope="col">Pay Rate Looking for</th>
            <th scope="col">Address</th>
            <th scope="col">Willing to Travel</th>
            <th scope="col">Certifications</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row"><%=contract.title %></th>
            <td><%= contract.availability_to_start %></td>
            <td><%= contract.aide.first_name %> <%= contract.aide.last_name %></td>
            <td><%= contract.aide.gender %></td>
            <td>$ <%= contract.pay_rate %>/ hr</td>
            <td><%= contract.aide.town_you_live_in %></td>
            <td><%= contract.aide.town_you_can_work %></td>
            <td><%= contract.aide.certifications %></td>
          </tr>
        </tbody>
    <% end %>
  </table>

  <hr>
  <br><br>

  <h2 class= "text-center"> All Clients in need of Igor Care </h2>
    <% @request_services.map do |request_service| %> 
      <% if request_service.request_jobs.count == 0 %>
        <table class="table table-warning">
          <thead>
            <tr>
              <th scope="col">Service</th>
              <th scope="col">Client</th>
              <th scope="col">Age</th>
              <th scope="col">Phone</th>
              <th scope="col">Location</th>
              <th scope="col">Prefers to work with </th>
              <th scope="col">Hours requested</th>
              <th scope="col">Comments</th>
              <th scope="col">Location</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row"><%= link_to request_service.service.title, new_request_job_path %></th>
              <td><%= request_service.client.first_name %> <%= request_service.client.last_name %> </td>
              <td><%= request_service.client.age %></td>
              <td><%= request_service.client.phone %></td>
              <td><%= request_service.client.town_you_live_in%></td>
              <td><%= request_service.client.preference_on_aides %> aides</td>
              <td><%= request_service.hours %> hrs a week </td>
              <td><%= request_service.comments %> </td>
              <td><%= request_service.location %>  </td>
            </tr>
          </tbody>
      <% end %>
    <% end %>
  </table>

  <hr> 
  <br><br>

  <h2 class= "text-center"> Current Jobs</h2>
    <% @request_jobs.map do |request_job| %> 
      <table class="table table-success">
        <thead>
          <tr>
            <th scope="col">Service</th>
            <th scope="col">Aide</th>
            <th scope="col">Aide's phone </th>
            <th scope="col">Client</th>
            <th scope="col">Client's phone</th>
            <th scope="col">Weekly hrs approved </th>
            <th scope="col">Approved Pay Rate</th>
            <th scope="col">Starting Date</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" id='link_to_job'><strong><%= link_to request_job.request_service.service.title, request_job_path(request_job) %></strong></th>
            <td> <%=request_job.aide.first_name %>  <%=request_job.aide.last_name %> </td>
            <td><%=request_job.aide.phone %></td>
            <td><%= request_job.request_service.client.first_name %> <%= request_job.request_service.client.last_name %></td>
            <td><%= request_job.request_service.client.phone %></td>
            <td><%= request_job.hours %></td>
            <td>$<%=request_job.pay_rate %> / hourly </td>
            <td><%= request_job.starting_date %> </td>
          </tr>
        </tbody>
    <% end %>
  </table>

  <hr> 

</div>

app/views/admins/login.html.erb
<div class="customized-container">
    <h2>Welcome back Admin</h2>
    <br>
        <% if @error %>
            <p><%= @error %></p>
        <% end %>
        <img src='https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80' alt='login-admin' id='login-img'>
        <%= form_tag "/send_the_form_here_3" do %>
            <strong><%= label_tag :first_name %></strong>
            <%= text_field_tag :first_name %><br>
            <strong><%= label_tag :password %></strong>
            <%= password_field_tag :password %><br>
            <%= submit_tag "LOGIN!", :class => "btn btn-success" %>
        <% end %>
</div>

app/views/admins/new.html.erb
<h1> You are in the new for admin</h1>


<%= form_for @admin do |f| %>
 <%= f.label :first_name %>
  <%= f.text_field :first_name %> <br/>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Ready!" %>
<% end %>

app/views/admins/show.html.erb
<h1>Welcome Master</h1>
<%= @current_admin.first_name %>