config/routes.rb
Rails.application.routes.draw do

  root to: 'users#homepage'

  resources :contracts
  resources :request_jobs
  resources :request_services
  resources :services
  resources :admins
  resources :clients
  resources :aides
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #HomePage 
  get '/home', to: 'users#homepage'
  # AboutPage 
  get '/about', to: "users#about"


# SERVICES 
get "/careers/:id", to: "services#career", as: 'career_path'


# GET THE AIDE THE LOGIN FORM
get "/login", to: "aides#login", as: "login"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here", to: "aides#handle_login"
delete "/logout", to: "aides#logout", as: "logout"
get "/profile", to: "aides#profile", as: "profile"


# GET THE CLIENT THE LOGIN FORM
get "/login_2", to: "clients#login", as: "login_2"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_2", to: "clients#handle_login"
delete "/logout_2", to: "clients#logout", as: "logout_2"
get "/my_profile", to: "clients#my_profile", as: "my_profile"


# GET THE ADMIN THE LOGIN FORM
get "/login_3", to: "admins#login", as: "login_3"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_3", to: "admins#handle_login"
delete "/logout_3", to: "admins#logout", as: "logout_3"
get "/admin_profile", to: "admins#profile", as: "admin_profile"

# EXTRA RENDER FOR SERVICES CONTROLLER 
get "jobs", to: 'services#job', as: 'jobs'

end

app/models/aide.rb
class Aide < ApplicationRecord
    has_many :contracts
    has_many :services, through: :contracts 
    has_many :request_jobs
    has_many :request_services, through: :request_jobs

    has_secure_password

    def full_name_and_contract_info
        self.first_name + ' ' + self.last_name + ' - ' + self.town_you_live_in 
    end

    def pay_rate_on_contract
        self.contracts.map(&:title)
    end 

end

app/controllers/aides_controller.rb
class AidesController < ApplicationController

    before_action :get_aide, only: [:show, :edit, :update, :destroy]
    before_action :authorized_to_see_page_aide
    skip_before_action :authorized_to_see_page_aide, only: [:login, :handle_login, :new, :create]

    def login
        @error = flash[:error]
    end

    def profile
        render :profile
    end
    
    def handle_login
        @aide = Aide.find_by(first_name: params[:first_name])
        if @aide && @aide.authenticate(params[:password])
        # If the aide is found AND their password matches
        session[:aide_id] = @aide.id
        redirect_to profile_path
        else
        flash[:error] = "Incorrect username or password"
        redirect_to login_path
        end
    end
    
    def logout
        session[:aide_id] = nil
        redirect_to login_path
    end
    
    def index 
        @aides = Aide.all 
    end 

    def show 
        @aide = Aide.find(params[:id])
    end 

    def new 
        @aide = flash[:errors]
        @aide = Aide.new 
    end 

    def create
        @aide = Aide.create(aide_params)
            if @aide.valid?
                session[:aide_id] = @aide.id
                redirect_to profile_path
            else 
                flash[:errors] = @aide.errors.full_messages
                redirect_to new_aide_path
            end
    end

    def edit 
        @aide = Aide.find(params[:id])
    end 

    def update
        @aide = Aide.find(params[:id])
        @aide.update(aide_params)
        redirect_to profile_path
    end 

    private 

    def get_aide
        @aide = Aide.find(params[:id])
    end

    def aide_params
        params.require(:aide).permit(:first_name, :last_name, :email, :age, :gender, :town_you_live_in, :town_you_can_work, :certifications, :password, :phone)
    end 

end

app/helpers/aides_helper.rb
module AidesHelper
end

app/views/aides/edit.html.erb
<div class="customized-container">

  <h1>Edit your profile <%=@aide.first_name %> </h1><br>

    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREHU2wEOzzvU8PPOO5Gv3J25I-9NluGdo8WQ&usqp=CAU">
      <br><br>

    <div class='form'>
      <%= form_for @aide do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %> <br/>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %><br/>
        <%= f.label :email %>
        <%= f.text_field :email %><br/>
        <%= f.label :phone %>
        <%= f.number_field :phone %><br/>
        <%= f.label :age %>
        <%= f.number_field :age %><br/>
        <%= f.label :gender %>
        <%= f.select :gender, options_for_select(["Male", "Female"]) %><br/>
        <%= f.label :town_you_live_in %>
        <%= f.select :town_you_live_in, options_for_select(["Brooklyn", "Queens", "Bronx", "Jamaica", "Manhattan", "Long Island"]) %><br/>
        <%= f.label :town_you_can_work %>
        <%= f.select :town_you_can_work, options_for_select(["Brooklyn", "Queens", "Bronx", "Jamaica", "Manhattan", "Long Island"]) %><br/>
        <%= f.label :certifications %>
        <%= f.select :certifications, options_for_select(["HHA Certification", "Nurse Certification", "HHA & Nurse Certification", "None"]) %><br/>
        <%= f.label :password %>
        <%= f.password_field :password %><br>
        <%= f.submit "DONE", :class => "btn btn-success", :id => 'submit' %>
      <% end %>
    </div>

</div>

app/views/aides/index.html.erb
<h1> Hello You are here </h1>

<h2> Join the team, check out the group. </h2>

<% @aides.map do |aide| %> 
<%= aide.first_name %> 
<% end %>

<br>

<%= link_to 'Explore Services', services_path %>

app/views/aides/login.html.erb
<div class="customized-container">
    <h2>Welcome back Aide</h2>
        <% if @error %>
            <p><%= @error %></p>
        <% end %>
        <%# THE FORM BELOW MAKES A POST REQUEST TO "/send_the_form_here" %>
        <img src='https://images.unsplash.com/photo-1590649613897-1d5c44ca3409?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80' alt='login aides' id='login-img'>
        <%= form_tag "/send_the_form_here/" do %>
            <strong><%= label_tag :first_name %></strong>
            <%= text_field_tag :first_name %><br>
            <strong><%= label_tag :password %></strong>
            <%= password_field_tag :password %><br><br>
            <%= submit_tag "LOGIN!", :class => "btn btn-success" %>
        <% end %>
</div>

app/views/aides/new.html.erb
<div class="customized-container">
  <h1>Start Your Application now </h1><br>

  <img src="https://scx2.b-cdn.net/gfx/news/2015/shouldthereb.jpg" alt='new-aide' id='sign-up'>
  <br><br>

<div class='form'>
  <%= form_for @aide do |f| %>
    <strong><%= f.label :first_name %></strong>
    <%= f.text_field :first_name %> <br/>
    <strong><%= f.label :last_name %>
    <%= f.text_field :last_name %><br/></strong>
    <strong><%= f.label :email %></strong>
    <%= f.text_field :email %><br/>
    <strong><%= f.label :phone %></strong>
    <%= f.number_field :phone %><br/>
    <strong><%= f.label :age %></strong>
    <%= f.number_field :age %><br/>
    <strong><%= f.label :gender %></strong>
    <%= f.select :gender, options_for_select(["Male", "Female"]) %><br/>
    <strong><%= f.label :town_you_live_in %></strong>
    <%= f.select :town_you_live_in, options_for_select(["Brooklyn", "Queens", "Bronx", "Jamaica", "Manhattan", "Long Island"]) %><br/>
    <strong><%= f.label :town_you_can_work %></strong>
    <%= f.select :town_you_can_work, options_for_select(["Brooklyn", "Queens", "Bronx", "Jamaica", "Manhattan", "Long Island"]) %><br/>
    <strong><%= f.label :certifications %></strong>
    <%= f.select :certifications, options_for_select(["HHA Certification", "Nurse Certification", "HHA & Nurse Certification", "None"]) %><br/>
    <strong><%= f.label :password %></strong>
    <%= f.password_field :password %><br>
    <%= f.submit "SIGN ME UP!", :class => "btn btn-success", :id => 'submit' %>
  <% end %>
</div>

</div>

app/views/aides/profile.html.erb
<div class="customized-container">
    <h2> Welcome to your Igor Space <%= @current_aide.first_name %> </h2>
    <br><br>
    

    <div class="card" style="width: 28rem;">
    <p class= 'text-center'> Your Profile</p>
        <img src="https://i1.sndcdn.com/avatars-000316683055-pz96wm-t500x500.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text"> <strong> Name:</strong> <%= @current_aide.first_name %> <%= @current_aide.last_name %><br/>
          <p class="card-text"> <strong> Email:</strong> <%= @current_aide.email %><br/>
          <p class="card-text"> <strong> Phone: </strong> <%= @current_aide.phone %><br/>
          <p class="card-text"> <strong> Age:</strong> <%= @current_aide.age %> years old <br/>
          <p class="card-text"> <strong> Locations I can work:</strong> <%= @current_aide.town_you_can_work %><br/>
          <p class="card-text"> <strong> Certifications:</strong> <%= @current_aide.certifications %><br/>
          <p class="card-text"> <strong> Member since:</strong> <%= @current_aide.created_at.strftime('%F') %><br/><br>
          </p>
        </div>
        <%= link_to "Adjust my Account", edit_aide_path(@current_aide), :class => 'btn btn-secondary' %> <br>
    </div>

    <br><br><br>



    <h2 class= 'text-center'> Applications Submitted</h2>
      <table class="table table-striped">
      <% @current_aide.contracts.map do |contract| %>
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
      <tbody>
        <tr>
          <th scope="row">Service:</th>
          <td><%= link_to contract.service.title, contract_path(contract)%></td>
        </tr>
        <tr>
          <th scope="row">Title:</th>
          <td><%= contract.title %></td>
        </tr>
        <tr>
          <th scope="row">My availablity to Start</th>
          <td> <%= contract.availability_to_start %></td>
        </tr>
        <tr>
          <th scope="row">Pay Rate I am looking for</th>
          <td>$ <%= contract.pay_rate %>/ hr</td>
        </tr>
          <tr>
          </tr>
      </tbody>
    <% end %>
    <tr>
    </tr>
</table>

<br><br><br>

  <h2 class= 'text-center'> Here are the cases you are working with</h2> <br>

<table class="table table-striped table-success">
  <% @current_aide.request_jobs.map do |cases| %>
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Location:</th>
          <td><%= cases.location %> </td>
        </tr>
        <tr>
          <th scope="row">Starting Date:</th>
          <td><%= cases.starting_date%> </td>
        </tr>
        <tr>
          <th scope="row">Pay Rate: $</th>
          <td> $ <%= cases.pay_rate %> hourly</td>
        </tr>
        <tr>
          <th scope="row">Hours granted for this case:</th>
          <td><%= cases.hours %> a week </td>
        </tr>
        <tr>
          <th scope="row">Client:</th>
          <td><%= cases.request_service.client.first_name %> <%= cases.request_service.client.last_name %> </td>
        </tr>
        <th scope="row">Client's Phone:</th>
          <td><%= cases.request_service.client.phone %></td>
        </tr>
        <tr>
      </tr>
  </tbody>
  <% end %>
    <tr>
    </tr>
</table>
<br><br> <br> <br>

<%= link_to "Apply to Services" , jobs_path, :class => "btn btn-success center" %>
<br><br> <br> <br>


</div>

app/views/aides/show.html.erb
<h1> this is the show page for aide</h1>

First Name: <%= @current_aide.first_name %><br>
Last Name: <%= @current_aide.last_name %><br>


    <% if @current_aide.contracts.count > 0 %>
 <p> Contracts you have as in right now  </p>

 <% @current_aide.contracts.map do |contract| %>
 <%= link_to contract.availability_to_start, contract_path(contract)  %> <br>
 <% end %>

 <% else %>

You have no contracts yet  

<% end %>
<br>

<%= link_to "Apply to Services" , services_path %>