config/routes.rb
Rails.application.routes.draw do

  root to: 'users#homepage'

  resources :contracts
  resources :request_jobs
  resources :request_services
  resources :services
  resources :admins
  resources :clients
  resources :aides
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #HomePage 
  get '/home', to: 'users#homepage'
  # AboutPage 
  get '/about', to: "users#about"


# SERVICES 
get "/careers/:id", to: "services#career", as: 'career_path'


# GET THE AIDE THE LOGIN FORM
get "/login", to: "aides#login", as: "login"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here", to: "aides#handle_login"
delete "/logout", to: "aides#logout", as: "logout"
get "/profile", to: "aides#profile", as: "profile"


# GET THE CLIENT THE LOGIN FORM
get "/login_2", to: "clients#login", as: "login_2"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_2", to: "clients#handle_login"
delete "/logout_2", to: "clients#logout", as: "logout_2"
get "/my_profile", to: "clients#my_profile", as: "my_profile"


# GET THE ADMIN THE LOGIN FORM
get "/login_3", to: "admins#login", as: "login_3"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_3", to: "admins#handle_login"
delete "/logout_3", to: "admins#logout", as: "logout_3"
get "/admin_profile", to: "admins#profile", as: "admin_profile"

# EXTRA RENDER FOR SERVICES CONTROLLER 
get "jobs", to: 'services#job', as: 'jobs'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all 
    end 

    def homepage 
    end 

    def about 
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class='customized-container'>
   <div class='sections'>
        <div id='about-header'>
            <h1>We are here for you </h1> <br>
            <button type="button" class="btn btn-primary" id='btn-design'><a class='link_to'href='/services'> SERVICES </a></button>
            <button type="button" class="btn btn-primary" id='btn-design'><a class='link_to'href='/jobs'> CAREERS </a></button>
        </div>
    </div>
    <br><%= image_tag 'heroes-home.jpg', :id =>'heroes-home-img'%>

    <div class='sections'>
        <h2>Where everything started</h2>
        <p class='sub-text'> In 2020, right at the moment when Covid-19 started, Igor Care was founded as a response to a new path in life. 
            The company was born with an idea and a goal on mind, to make a difference in people's life. 
            Thanks to the help of our investors, we have numerous compassionate and professionals ready to step in, and care with passion for families, and friends.
                <br>
            Igor Care seeks to become a trusted leader in providing a full range of services oriented for middle aged and elder groups. Our lines are ready to serve you at our best from 9:00 am to 5:00 pm from Mondays to Fridays.
        </p>
    </div>
    
    <div class='sections'>
        <h2>Who we are </h2>
        <%= image_tag 'office-workers.jpg', :id =>'office-workers-img'%>


        <p class='sub-text'>At Igor Care we do not discrimate based on gender, color, education, race, nor relegion. We take pride in our members and strongly believe in ownership, 
        given the right mindset, and determination, you can scalate the ladder of the company, and become a leader among colleages.</p>
    </div>
</div>

app/views/users/homepage.html.erb
<div class='customized-container'>
    <div class='home-alignment'>
        <h1 class='home_header'>Igor care<br> where you come first </h1>
        <p>We are here with you, every single step of the way</p>
        <%= image_tag 'together.jpg', :id =>'together-img' %>

        <p class='sub-text'> Igor Care was founded as a response to the necessity of our community. Our mission is to provide the best health care to our clients, whether it is at home or in a nursing facility, we bring options to you.
        From nurses, therapists, aides in the home, to the hundreds of committed employees supporting thier work from our offices all around the New York City Metropolitan Area, giving you the best care is our highest priority and notable joy. </p>

        <div class="container" id='paragraph'>
            <div class="row">
                <div class="col-md-8">
                    <h1>Let us join you</h1>
                    <p>Choose from a family member, a close friend our one of our qualified aide to make your daily life a more joyful one</p>
                    <button class='btn btn-primary' id='btn-font'><%= link_to 'EXPLORE', services_path %></button>

                </div>
                <div class="col-md-4">
                    <%= image_tag 'close-friend.jpg', :id=>'close-friend' %>
                </div>
            </div>
        </div>

        <div class='container' id='paragraph'>
            <div class='row'>
                <div class="col-md-4">
                    <%= image_tag 'home-health-aide.jpg', :id=>'home-health-aide' %>
                </div>
                <div class="col-md-8">
                    <h1>Help us a change a life</h1>
                    <p>Join our team, and make a difference on someone's life, become a hero while getting higher pay rates.</p>
                    <button class='btn btn-primary' id='btn-font'><%= link_to 'EXPLORE', jobs_path %></button>
                </div>
            </div>
        </div>

        <p class='sub-text'> At Igor's Care we put our family first. Our heart is in everything we do. We exist to help people to have a safe life at home, this is not just our mission, but our vision, beliefs and core values that define our culture and embodies our essence at work. </p>
    </div>
</div>

app/views/users/index.html.erb
<h1> This is the user index page </h1>


<% @users.map do |user|%>
<%= user.first_name %>
<% end %>



<br>
<br>

<%= link_to "View Services", services_path %>

app/views/users/login.html.erb
<h1>Hello, This is Where the Login Form Goes</h1>



<% if @error %>
    <p><%= @error %></p>
<% end %>

<%# THE FORM BELOW MAKES A POST REQUEST TO "/send_the_form_here" %>

<%= form_tag "/send_the_form_here" do %>
    <%= label_tag :first_name %>
    <%= text_field_tag :first_name %>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <%= submit_tag "Login!" %>
<% end %>

app/views/users/new.html.erb
<h1>This is the new for user</h1>

<%= form_for @user do |f| %>
 <%= f.label :first_name %>
  <%= f.text_field :first_name %> <br/>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.label :role %>
  <%= f.select :role, options_for_select(["aide", "client"]) %><br/>
  <%= f.label :password %>
  <%= f.text_field :password %>
  


 
  

  <%= f.submit "Ready!" %>
<% end %>

<br>
<br>
<%= link_to "Log In", login_path %>

app/views/users/show.html.erb
<h1>This is the show for user </h1>

<%= @user.first_name %> -- as <%= @user.role %>