config/routes.rb
Rails.application.routes.draw do

  root to: 'users#homepage'

  resources :contracts
  resources :request_jobs
  resources :request_services
  resources :services
  resources :admins
  resources :clients
  resources :aides
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #HomePage 
  get '/home', to: 'users#homepage'
  # AboutPage 
  get '/about', to: "users#about"


# SERVICES 
get "/careers/:id", to: "services#career", as: 'career_path'


# GET THE AIDE THE LOGIN FORM
get "/login", to: "aides#login", as: "login"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here", to: "aides#handle_login"
delete "/logout", to: "aides#logout", as: "logout"
get "/profile", to: "aides#profile", as: "profile"


# GET THE CLIENT THE LOGIN FORM
get "/login_2", to: "clients#login", as: "login_2"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_2", to: "clients#handle_login"
delete "/logout_2", to: "clients#logout", as: "logout_2"
get "/my_profile", to: "clients#my_profile", as: "my_profile"


# GET THE ADMIN THE LOGIN FORM
get "/login_3", to: "admins#login", as: "login_3"
# HANDLE THE LOGIN FORM SUBMISSION
post "/send_the_form_here_3", to: "admins#handle_login"
delete "/logout_3", to: "admins#logout", as: "logout_3"
get "/admin_profile", to: "admins#profile", as: "admin_profile"

# EXTRA RENDER FOR SERVICES CONTROLLER 
get "jobs", to: 'services#job', as: 'jobs'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthCareAgency</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta property=”og:title” content=”Igor Care” /> 
      <meta property=”og:type” content=”website” /> 
      <meta property=”og:url” content=”https://peaceful-headland-40438.herokuapp.com/” /> 
      <meta property=”og:image” content=”a-facade.png” /> 
      <meta property=”og:description” content=”A web application that has 3 different types of users, where health requests are made and addressed.” />

      <%# Google Fonts %>
      <link rel="preconnect" href="https://fonts.gstatic.com">

      <link href="https://fonts.googleapis.com/css2?family=Della+Respira&family=IM+Fell+English&display=swap" rel="stylesheet">

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src='https://kit.fontawesome.com/a076d05399.js'></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id='navbar'>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active ">
            <a class='nav-link ' href='/home'>Home</a>
          </li>
          <li class="nav-item">
            <a class='nav-link ' href='/about' >About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/services">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href='/home' ><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZ8RtuO_70AQoPgg62TjUKraxYjcbgD7ge6g&usqp=CAU' id='logo-image'></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/jobs">Careers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#staticBackdrop">Contact Us</a>
          </li>
            <% if check_and_see_if_someone_is_logged_in_as_aide? %>
              <nav class="nav flex-column">
                <a class="nav-link"><%= link_to "My Profile", profile_path, method: :get, :class => "btn-primary", :id => 'nav-no-decoration'%></a>
                <a class="nav-link"><%= button_to "Log Out", logout_path, method: :delete, :class => "btn-danger", :id => 'nav-no-decoration' %></a>
              </nav>

            <% elsif check_and_see_if_someone_is_logged_in_as_client? %>
              <nav class="nav flex-column">
                <a class="nav-link"><%= link_to "My Profile", my_profile_path, method: :get, :class => "btn-primary", :id => 'nav-no-decoration'%></a>
                <a class="nav-link"><%= button_to "Log Out", logout_2_path, method: :delete, :class => "btn-danger", :id => 'nav-no-decoration' %></a>
              </nav>

            <% elsif check_and_see_if_someone_is_logged_in_as_admin? %>
              <nav class="nav flex-column">
                <a class="nav-link"><%= link_to "My Profile", admin_profile_path, method: :get, :class => "btn-primary", :id => 'nav-no-decoration'%></a>
                <a class="nav-link"><%= button_to "Log Out", logout_3_path, method: :delete, :class => "btn-danger", :id => 'nav-no-decoration' %></a>
              </nav>

            <% else %>            
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Log in</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/login">Aides </a>
                <a class="dropdown-item" href="/login_2">Clients</a>
                <a class="dropdown-item" href="/login_3">Admin</a>
              </div>
          </li>

          <% end %>
 
        </ul>
      </div>
    </nav>
    
      

    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Page under Re-constructions.</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Sorry for the inconvenience
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>


    <%= yield %>

    <!-- Footer -->
<div class='footer-container'>
  <h5 class="text-uppercase" id='footer-igorCare'>IGOR CARE</h5>
      <div class="row">
        <div class="col-sm-4">
          <div class="card" id='card3'>
            <div class="card-body">
              <h5 class="card-title"><strong>Our Culture</strong></h5>
              <p class="card-text">
              <p><a id='footer-link' href='/about' >About</a></p>
              <p><a id='footer-link' href='/services' >Services</a></p></p>
              <p><a id='footer-link' href='/jobs' >Careers</a></p></p>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card" id='card3'>
            <div class="card-body">
              <h5 class="card-title"><strong>Contact</strong></h5>
              <p class="card-text">123 Main Rd. New York, NY 11321</p>
              <p class="card-text">Phone: (718) 343 - 4343</p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card" id='card3'>
            <div class="card-body">
              <h5 class="card-title"><strong>Connect with us</strong></h5>
              <p class="card-text">
                <p><a href='https://www.linkedin.com/in/franklin-bado/'><i style='font-size:24px' class='fab'>&#xf0e1;</i>franklin-bado</a></p>
                <p><a href='https://github.com/fbado66'><i style='font-size:24px' class='fab'>&#xf09b;</i>fbado66</a></p>
                <p><a href='https://medium.com/@fbado66'><i style='font-size:24px' class='fab'>&#xf3c7;</i>@fbado66</a></p>
              </p>
            </div>
          </div>
        </div>
      </div>
    <p>©2020 Igor Care. All Rights Reserved. This is a demo for a fictious Health Care Company</p>
  </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


  </body>
</html>